In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:/Datasets/ESAM/BKP_ALUMNOS_20260915_ESAM.csv")
df.head(5)

,Cod_Unico,Cod_Academico,Id_Portal,Cod_Contable,Programa,Gestion,Tipo,Sede,Convenio,id_ins_portal,...,Monto_MatCol_Ingresado,Monto_Total_Liquidado,Fecha_Ultimo_Pago,Concepto_Ultimo_Pago,Estado_Ins_Portal,Estado_Admin_Portal,Estado_Acad_Portal,Fecha_Cambio_Estado,Estado_Cartera_Portal,Estado_Admin_Sistema
0,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,1,...,0.0,0.0,1900-01-01,sin definir,Inscrito,Inscrito,Concluido,2026-06-24,Exento de deuda,Inscrito
1,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,2,...,0.0,0.0,1900-01-01,sin definir,Inscrito,Inscrito,Concluido,2025-04-21,Exento de deuda,Inscrito
2,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,3,...,0.0,0.0,1900-01-01,sin definir,Inscrito,Inscrito,Concluido,2025-04-21,Exento de deuda,Inscrito
3,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,4,...,0.0,0.0,1900-01-01,sin definir,Inscrito,Inscrito,Concluido,2026-06-24,Exento de deuda,Inscrito
4,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,5,...,0.0,0.0,1900-01-01,sin definir,Inscrito,Inscrito,Concluido,2025-04-21,Exento de deuda,Inscrito

92587
91939
90737
91542
90294
93796
97672
93809

In [4]:
consulta1 = df[df["id_ins_portal"].isin([133537,55732,56788])][["CI", "Alumno", "Cod_Academico", "Estado_Admin_Portal", "Estado_Acad_Portal", "Fecha_Cambio_Estado", "Estado_Cartera_Portal", "Estado_Admin_Sistema"]]
consulta1

,CI,Alumno,Cod_Academico,Estado_Admin_Portal,Estado_Acad_Portal,Fecha_Cambio_Estado,Estado_Cartera_Portal,Estado_Admin_Sistema
25421,12813118,Soliz Michel Laura Patricia,PT-PPO-22-14-01-01,Preinscrito,Concluido,2026-04-18,Exento de deuda,Inscrito
25711,8648400,Gomez Flores Marianela Beatriz,PT-PPO-22-14-01-01,Preinscrito,Concluido,2026-04-18,Exento de deuda,Inscrito
58196,8022048,Fuentes Calatayud Leonardo,MAR-N-D1124,Retirado,Abandono académico,2026-03-18,Liquidado,Retirado

In [ ]:
consulta2 = df[df["id_ins_portal"].isin([139192])][["CI", "Estado_Admin_Portal", "Estado_Acad_Portal", "Fecha_Cambio_Estado", "Estado_Cartera_Portal", "Estado_Admin_Sistema"]]
consulta2