In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:/Datasets/ESAM/BKP_ALUMNOS_20260803_ESAM.csv")
df.head(5)

,Cod_Unico,Cod_Academico,Id_Esam,Cod_Contable,Programa,Gestion,Tipo,Sede,Convenio,Id_Inscripcion,...,Id_Detalle_Pago,Concepto_Ultimo_Pago,Tram_Personal,Estado_Administrativo,Estado_Academico,Estado_Esam,Estado_Esam_Real,Estado_Sistema,Estado_Cartera,Fecha_ceacion
0,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,1,...,-,sin definir,0.0,Inscrito,Concluido Aprobado,Inscrito,Inscrito,Inscrito,Exento de deuda,2019-11-26 08:38:35
1,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,2,...,-,sin definir,0.0,Inscrito,Concluido Aprobado,Inscrito,Inscrito,Inscrito,Exento de deuda,2019-11-26 08:38:35
2,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,3,...,-,sin definir,0.0,Inscrito,Concluido Aprobado,Inscrito,Inscrito,Inscrito,Exento de deuda,2019-11-26 08:38:35
3,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,4,...,-,sin definir,0.0,Inscrito,Concluido Aprobado,Inscrito,Inscrito,Inscrito,Exento de deuda,2019-11-26 08:38:35
4,576,R-EM20-003,D-129,DIQ-8018,Diplomado En Instrumentación Quirúrgica V-1 G-...,2019,Diplomado,Esam Tarija 2,UNSXX,5,...,-,sin definir,0.0,Inscrito,Concluido Aprobado,Inscrito,Inscrito,Inscrito,Exento de deuda,2019-11-26 08:38:35

92587
91939
90737
91542
90294
93796
97672
93809

In [6]:
consulta1 = df[df["Id_Inscripcion"].isin([237090])][["Id_Inscripcion","Programa","Sede","ALUMNO","CI","Estado_Administrativo","Estado_Esam","Estado_Academico","estado_cartera","monto_pagado_fase_formativa","monto_pagado_certificacion"]]
consulta1

KeyError: "['ALUMNO', 'estado_cartera', 'monto_pagado_fase_formativa', 'monto_pagado_certificacion'] not in index"

In [ ]:
consulta2 = df[df["Estado_Administrativo"].isin(["Prospecto"])][["Id_inscripcion","Programa","Sede","ALUMNO","CI","Estado_Administrativo", "Estado_Esam","Estado_Academico","estado_cartera","monto_pagado_fase_formativa","monto_pagado_certificacion"]]
consulta2

,Id_inscripcion,Programa,Sede,ALUMNO,CI,Estado_Administrativo,Estado_Esam,Estado_Academico,estado_cartera,monto_pagado_fase_formativa,monto_pagado_certificacion
92,125,Maestría En Derecho Procesal Penal V-2 G-2 S-2...,Esam Tarija 2,HUANCA AYLLON RICARDO,7189997,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
94,127,Maestría En Derecho Procesal Penal V-2 G-2 S-2...,Esam Tarija 2,Medina Salinas Mario Antonio,5056682,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
101,134,Maestría En Derecho Procesal Penal V-2 G-2 S-2...,Esam Tarija 2,Soliz Choque Alex Walter,5047471,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
104,137,Maestría En Derecho Procesal Penal V-2 G-2 S-2...,Esam Tarija 2,BAUTISTA BAYON ELIZABETH,5785521,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
105,138,Maestría En Derecho Procesal Penal V-2 G-2 S-2...,Esam Tarija 2,RIOS LENES EVER JHONNY,7256492,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
95174,222458,MAESTRÍA EN EDUCACIÓN SUPERIOR POR COMPETENCIA...,Esam Cochabamba,Maldonado Quiroz Jhoset Celina,9328991,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
95190,222509,MAESTRÍA EN SALUD PÚBLICA CON MENCIÓN EN EPIDE...,Esam Cochabamba,Callejas Maturano Jovana,8889713,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
95214,222566,Maestría En Derecho Civil Y Procesal Civil (V2...,Esam Oruro,Clavel flores Milenka Nancy,4811240,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0
95215,222568,MAESTRÍA EN INGENIERÍA VIAL CON MENCIÓN EN CAR...,Esam Oruro,Calani Gabriel Jhonny Cesar,3547764,Prospecto,Inscrito,sin definir,Vigente,200.0,0.0
95216,222569,MAESTRÍA EN SALUD PÚBLICA CON MENCIÓN EN EPIDE...,Esam Cochabamba,Vasquez Reynaga Edgar Felix,690756,Prospecto,Preinscrito,sin definir,Sin cartera asignada,0.0,0.0